<a href="https://colab.research.google.com/github/JunHL96/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


### If Apple Silicon User:

In [2]:
mps = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"MPS Available: {torch.backends.mps.is_available()}")

MPS Available: False


## Introduction to Tensors


### What are tensors?

A tensor is a multi-dimensional matrix containing elements of a single data type.

### Creating tensors

PyTorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html



In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector (magnitude, direction)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

## Matrix

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])


In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape # torch.Size([2, 2]) which means 2x2 or 2 by 2

torch.Size([2, 2])


<details>

### `.shape`
- **Returns the dimensions of the tensor (or array)** as a tuple.
- Each element of the tuple (an ordered, immutable collection of items) represents the size of the tensor in that dimension.

Example:
```python
vector = torch.tensor([7, 7])
print(vector.shape)  # Output: torch.Size([2])
```

### `.ndim`
- **Returns the number of dimensions (rank) of the tensor.**
- this is an integer value representing how many dimensions the tensor has

Example:
```python
vector = torch.tensor([7, 7])
print(vector.ndim)  # Output: 1
```

### Explanation:
- `vector = torch.tensor([7, 7])` creates a 1D tensor (vector) with 2 elements.
- `.shape` gives `(2)` because the vector has 2 elements in one dimension.
- `.ndim` gives `1` because the tensor is 1-dimensional.


| Attribute  | Description                               | Example Output            |
|------------|-------------------------------------------|---------------------------|
| `.shape`   | Tuple representing the size of each dimension | `torch.Size([2])`   |
| `.ndim`    | Integer representing the number of dimensions | `1`                       |

</details>

## Tensors


In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape # the result is torch.Size([1, 3, 3]), meaning we have one 3x3 tensor

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Image Representation
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

## Random Tensors

### Why Random Tensors?
Random tensors are important b/c the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

### Documentation of torch.rand
https://pytorch.org/docs/stable/generated/torch.rand.html


In [18]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5296, 0.9003, 0.0687, 0.4204],
        [0.9392, 0.2044, 0.1042, 0.9797],
        [0.8274, 0.8518, 0.9654, 0.4990]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones Tensors

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
random_tensor.dtype # check data type of our random tensor

torch.float32

## Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step = 1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big potential errors you'll run into with PyTorch & Deep Learning:
1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32, float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting Information from Tensors

1. Tensors are not the right datatype - to get detatype from a tensor, can use `tensor.dtype`
2. Tensors are not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors are not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Create a tensor
test_tensor = torch.rand(3, 4)
test_tensor

tensor([[0.4481, 0.0407, 0.7350, 0.0213],
        [0.8630, 0.2048, 0.2037, 0.2421],
        [0.9388, 0.8026, 0.9857, 0.3678]])

In [33]:
# Find out Tensor Attributes
print(test_tensor)
print(f"Datatype of tensor: {test_tensor.dtype}")
print(f"Shape of tensor: {test_tensor.shape}")
print(f"Device tensor is on: {test_tensor.device}")

tensor([[0.4481, 0.0407, 0.7350, 0.0213],
        [0.8630, 0.2048, 0.2037, 0.2421],
        [0.9388, 0.8026, 0.9857, 0.3678]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

Usually, manipulating tensors will include a combination of the above.

In [43]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10) # Generally, you want to use Python functions instead

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot-product)

The main two rules for matrix multiplication to remember are:

* The inner dimensions must match: \\
(3, 2) @ (3, 2) won't work \\
(2, 3) @ (3, 2) will work \\
(3, 2) @ (2, 3) will work \\
* The resulting matrix has the shape of the outer dimensions: \\
(2, 3) @ (3, 2) -> (2, 2) \\
(3, 2) @ (2, 3) -> (3, 3)

```
Note: "@" in Python is the symbol for matrix multiplication.
```
```
Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.
```




In [49]:
# Element-wise multiplication
print(tensor, "*", * tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor(1) tensor(2) tensor(3)
Equals: tensor([1, 4, 9])


In [50]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.96 ms, sys: 1.01 ms, total: 3.97 ms
Wall time: 3.88 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

# we see that the in-built function is much more optimized

CPU times: user 688 µs, sys: 0 ns, total: 688 µs
Wall time: 566 µs


tensor(14)