<a href="https://colab.research.google.com/github/JunHL96/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/




In [268]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


### If Apple Silicon User:

In [269]:
mps = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"MPS Available: {torch.backends.mps.is_available()}")

MPS Available: False


## Introduction to Tensors


### What are tensors?

A tensor is a multi-dimensional matrix containing elements of a single data type.

### Creating tensors

PyTorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html



In [270]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [271]:
scalar.ndim

0

In [272]:
# Get tensor back as Python int
scalar.item()

7

In [273]:
# Vector (magnitude, direction)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [274]:
vector.ndim

1

In [275]:
vector.shape

torch.Size([2])

## Matrix

In [276]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])


In [277]:
MATRIX.ndim

2

In [278]:
MATRIX[0]

tensor([7, 8])

In [279]:
MATRIX[1]

tensor([ 9, 10])

In [280]:
MATRIX.shape # torch.Size([2, 2]) which means 2x2 or 2 by 2

torch.Size([2, 2])


<details>

### `.shape`
- **Returns the dimensions of the tensor (or array)** as a tuple.
- Each element of the tuple (an ordered, immutable collection of items) represents the size of the tensor in that dimension.

Example:
```python
vector = torch.tensor([7, 7])
print(vector.shape)  # Output: torch.Size([2])
```

### `.ndim`
- **Returns the number of dimensions (rank) of the tensor.**
- this is an integer value representing how many dimensions the tensor has

Example:
```python
vector = torch.tensor([7, 7])
print(vector.ndim)  # Output: 1
```

### Explanation:
- `vector = torch.tensor([7, 7])` creates a 1D tensor (vector) with 2 elements.
- `.shape` gives `(2)` because the vector has 2 elements in one dimension.
- `.ndim` gives `1` because the tensor is 1-dimensional.


| Attribute  | Description                               | Example Output            |
|------------|-------------------------------------------|---------------------------|
| `.shape`   | Tuple representing the size of each dimension | `torch.Size([2])`   |
| `.ndim`    | Integer representing the number of dimensions | `1`                       |

</details>

## Tensors


In [281]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [282]:
TENSOR.ndim

3

In [283]:
TENSOR.shape # the result is torch.Size([1, 3, 3]), meaning we have one 3x3 tensor

torch.Size([1, 3, 3])

In [284]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Image Representation
https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

## Random Tensors

### Why Random Tensors?
Random tensors are important b/c the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

### Documentation of torch.rand
https://pytorch.org/docs/stable/generated/torch.rand.html


In [285]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9289, 0.6977, 0.4915, 0.0939],
        [0.8060, 0.2352, 0.1625, 0.9581],
        [0.3598, 0.8204, 0.3931, 0.4592]])

In [286]:
random_tensor.ndim

2

In [287]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones Tensors

In [288]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [289]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [290]:
random_tensor.dtype # check data type of our random tensor

torch.float32

## Creating a range of tensors and tensors-like

In [291]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step = 1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [292]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big potential errors you'll run into with PyTorch & Deep Learning:
1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [293]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32, float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [294]:
float_32_tensor.dtype

torch.float32

In [295]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [296]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [297]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting Information from Tensors

1. Tensors are not the right datatype - to get detatype from a tensor, can use `tensor.dtype`
2. Tensors are not the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors are not on the right device - to get device from a tensor, can use `tensor.device`

In [298]:
# Create a tensor
test_tensor = torch.rand(3, 4)
test_tensor

tensor([[0.3957, 0.0390, 0.3845, 0.7895],
        [0.3166, 0.0292, 0.4739, 0.5264],
        [0.9433, 0.4791, 0.6244, 0.1668]])

In [299]:
# Find out Tensor Attributes
print(test_tensor)
print(f"Datatype of tensor: {test_tensor.dtype}")
print(f"Shape of tensor: {test_tensor.shape}")
print(f"Device tensor is on: {test_tensor.device}")

tensor([[0.3957, 0.0390, 0.3845, 0.7895],
        [0.3166, 0.0292, 0.4739, 0.5264],
        [0.9433, 0.4791, 0.6244, 0.1668]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

Usually, manipulating tensors will include a combination of the above.

In [300]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [301]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [302]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [303]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10) # Generally, you want to use Python functions instead

tensor([10, 20, 30])

In [304]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot-product)

The main two rules for matrix multiplication to remember are:

* The inner dimensions must match: \\
(3, 2) @ (3, 2) won't work \\
(2, 3) @ (3, 2) will work \\
(3, 2) @ (2, 3) will work \\
* The resulting matrix has the shape of the outer dimensions: \\
(2, 3) @ (3, 2) -> (2, 2) \\
(3, 2) @ (2, 3) -> (3, 3)

```
Note: "@" in Python is the symbol for matrix multiplication.
```
```
Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.
```




In [305]:
# Element-wise multiplication
print(tensor, "*", * tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor(1) tensor(2) tensor(3)
Equals: tensor([1, 4, 9])


In [306]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [307]:
# Matrix multiplication by hand
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)
# avoid doing operations with for loops b/c they are computationally expensive

tensor(14)
CPU times: user 2.41 ms, sys: 0 ns, total: 2.41 ms
Wall time: 2.28 ms


In [308]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

# we see that the in-built function is much more optimized

CPU times: user 87 µs, sys: 0 ns, total: 87 µs
Wall time: 91.8 µs


tensor(14)

In [309]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3203, 0.3562, 0.1472],
        [0.6079, 0.4078, 0.2230],
        [1.4472, 0.8684, 0.5093]])

In [310]:
torch.matmul(torch.rand(2, 10), torch.rand(10, 3))

# remember, resulting matrix has shape of outer dimensions

tensor([[2.6703, 1.1990, 1.7664],
        [3.1029, 1.1407, 1.8624]])

### One of the most common errors in Deep Learning: Shape Errors

In [311]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (alias)
#torch.matmul(tensor_A, tensor_B)

In [312]:
# Check tensor sizes to make sure they are compatible for matrix multiplication
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [313]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [314]:
# transpose switches the dimensions from 3x2 to 2x3
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [315]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match\n")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [316]:
# Create a tensor
x = torch.arange(0, 100, 10) # torch.arange(start, end, step)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [317]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [318]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [319]:
# Find the mean
#torch.mean(x), x.mean() # This will result in an error because x is not a float tensor

# mean() input dtype should be either floating point or complex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [320]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [321]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin() # This returns index position of target tensor where the minimum value occurs

tensor(0)

In [322]:
x[0] # This returns the actual minimum value

tensor(0)

In [323]:
# Find the position in tensor that has the maximum value with argmax()
x. argmax()

tensor(9)

In [324]:
x[9] # This returns the actual maximum value

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor into a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [325]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [326]:
# Add an extra dimension to the tensor

# x.reshape(dim1, dim2, ..., dimN) # Dimension must have the same number of elements as the original tensor
#x_reshaped = x.reshape(1, 7) # Error occurs because reshaping to (1, 7) is invalid as the total number of elements must remain the same.
#x_reshaped = x.reshape(2, 9) # Error occurs because this would require 18 elements, but we only have 9.
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [327]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [328]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [329]:
# Stack tensors on top of each other

# Stack tensors on top of each other along the first dimension (rows), creating a 2D tensor.
x_stacked = torch.stack([x, x, x, x], dim=0)

# Stack tensors side by side along the second dimension (columns), creating a 2D tensor.
#x_stacked = torch.stack([x, x, x, x], dim=1)

# Attempt to stack tensors along the third dimension, but this will result in an error for 1D tensors.
#x_stacked = torch.stack([x, x, x, x], dim=2)

x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [330]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [331]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [332]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [333]:
# torch.permute - rearranges the dimensions of a target tensor of a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Remember the purpose of reshaping, stacking, squeezing, and unsqueezing tensors: these help us fix shape and dimension issues with tensors, which is the most common error in Deep Learning and Neural Networks.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [334]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [335]:
# Let's index on our new tensor
x[0], x[0].shape # Indexing on the first dimension (batch dimension)

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [336]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0][0].shape # Indexing on the second dimension

(tensor([1, 2, 3]), torch.Size([3]))

In [337]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][0][0].shape # Indexing on the third dimension


(tensor(1), torch.Size([]))

In [338]:
# Play around with the indexing!
x[0][1][1], x[0][1][1].shape

(tensor(5), torch.Size([]))

In [339]:
# Play around with the indexing!
x[0][1][1], x[0][1][1].shape # note that for our current tensor, x[1][0][0] will give us an error b/c the index is out of bounds for current tensor

(tensor(5), torch.Size([]))

In [340]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [341]:
# Get all values across the 0th and 1st dimensions, but only the 2nd index of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [342]:
# Get all values across the 0th dimension, but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1] # retrieves all elements from 0th dimension, grabs the element at index 1 in 1st dimension, grabs the element at index 1 in 2nd dimension

# Note that this is very similar to x[0][1][1] except we have an extra dimension [ ]

tensor([5])

In [343]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # equivalent to x[0][0]

tensor([1, 2, 3])

Start video on - 3:32:28 \\
https://www.youtube.com/watch?v=Z_ikDlimN6A&list=PL4bBPBIa3Hi-fOOqMAX3pIigMfkv4Cbyk